<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Salarioanodb;

use Atlas\Table\Table;

/**
 * @method SalarioanodbRow|null fetchRow($primaryVal)
 * @method SalarioanodbRow[] fetchRows(array $primaryVals)
 * @method SalarioanodbTableSelect select(array $whereEquals = [])
 * @method SalarioanodbRow newRow(array $cols = [])
 * @method SalarioanodbRow newSelectedRow(array $cols)
 */
class SalarioanodbTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'salarioanodbs';

    const COLUMNS = [
        'ID' => [
            'name' => 'ID',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'ano' => [
            'name' => 'ano',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'vigencia' => [
            'name' => 'vigencia',
            'type' => 'VARCHAR',
            'size' => 150,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'valor' => [
            'name' => 'valor',
            'type' => 'REAL',
            'size' => 8,
            'scale' => 2,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'atoLegal' => [
            'name' => 'atoLegal',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'ID',
        'ano',
        'vigencia',
        'valor',
        'atoLegal',
    ];

    const COLUMN_DEFAULTS = [
        'ID' => null,
        'ano' => null,
        'vigencia' => null,
        'valor' => null,
        'atoLegal' => null,
    ];

    const PRIMARY_KEY = [
        'ID',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
